import Project from '@components/Project'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import axios from 'axios'
import Calender from '@components/Calendar.js'
import EventForm from '@components/EventForm'
import { AppContext } from 'context/ContextWrapper'

import styles from './Home.module.css'

export default function Home() {
  const { setSaveEvents } = useContext(AppContext)
  const [SaveProject, setSaveProject] = useState([])

  // fetch data form api

  const projectUrl = '/api/Projects'
  const EventUrl = '/api/Events'

  const projectReq = axios.get(projectUrl)
  const eventReq = axios.get(EventUrl)

  useEffect(() => {
    axios
      .all([projectReq, eventReq])
      .then(
        axios.spread((...responses) => {
          const projectRes = responses[0].data
          const eventRes = responses[1].data

          setSaveProject(projectRes)
          setSaveEvents(eventRes)
        })
      )
      .catch((err) => {
        console.error(err)
      })
  }, [SaveProject, setSaveEvents])

  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <EventForm project={SaveProject} />
        <Project project={SaveProject} />
        <Calender />
      </div>
    </section>
  )
}
